<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<div class="page-title"><h2><?php echo $this->getPageHeading(); ?></h2></div>

<?php $_productCollection=$this->getProductCollection() ?>

<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>

<article class="category-products">
<div class="spinner"></div>
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
	<ol class="products-list" id="products-list">    
    <?php foreach ($_productCollection as $_product): ?>
        <li class="hproduct item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
			
            
			 <div class="products_list_left">
			 <!-- =============  Start New / Sale Label ===== -->
			<?php if($this->helper('framework')->isSpecialProduct($_product)):?>
					<div class="sale-label"><?php echo $this->__('Sale Label') ?></div>
			<?php endif; ?>	
			<!-- =============  End New / Sale Label ===== -->
			 
			 <div class="product_back">
				<div  class="product_iner">
				 
			
				
			<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image url">
			<?php if($this->helper('framework')->getAspectRatio()):?>				
					<img class="photo fn" src="<?php echo $this->helper('adaptiveResize/image')->init($_product, 'small_image')->setCropPosition('top')->adaptiveResize(180,200); ?>" width="180" height="200" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
				<?php else:	?>	
					<img class="photo fn" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(180,200); ?>" width="180" height="200" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />			
				<?php endif; ?>	
			
			</a>
			</div></div>
			</div>
			
            <div class="products_list_center">
                <div class="f-fix">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
					
					<h2 class="item fn product-name" ><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName())?></a></h2>
					
                    <?php if($_product->getRatingSummary()): ?>
                    <div class="description"><?php echo $this->getReviewsSummaryHtml($_product) ?></div>
                    <?php endif; ?>
                  
                    
                
					
					<div class="desc std">
					  <?php 
							$str = strlen($_product->getShortDescription());
							if($str <= 300 )
							{
								echo $_product->getShortDescription();  ?>						
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="link-learn">
									<?php echo $this->__('Learn More') ?>
								</a>
							<?php }
							else
							{
								echo substr($_product->getShortDescription(),0,300);  ?>							
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="link-learn">
								 <?php echo $this->__('Learn More') ?>
							   </a>
						<?php } ?>
                    </div>
					
                     
					 <?php if($this->helper('framework')->getAddtoLinksList()):?>
						<ul class="add-to-links">
							<?php if(!$this->helper('framework')->isActiveWishlist()):?>						
								<?php if ($this->helper('wishlist')->isAllow()) : ?>
									
									<?php if($this->helper('framework')->getAddtoLinksListIcon()):?>
										<li class="wishlist_image">
											<a rel="nofollow"  href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>">
											<img src="<?php echo $this->getSkinUrl('images/link_wishlist_icon.png')?>" alt="" /></a>
										</li>	
									<?php else: ?>
										<li class="wishlist_text">
										<a rel="nofollow"  href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist">
										<?php echo $this->__('Add to Wishlist') ?></li></a>
									<?php endif; ?>
										
								<?php endif; ?>
							<?php endif; ?>	
							
							<?php if(!$this->helper('framework')->isActiveCompare()):?>
								<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
								
								<?php if($this->helper('framework')->getAddtoLinksListIcon()):?>
									<li class="compare_image">
										<a rel="nofollow" href="<?php echo $_compareUrl ?>">
											<img src="<?php echo $this->getSkinUrl('images/link_compare_icon.png')?>" alt="" />										
										</a>
									</li>	
									<?php else: ?>
									<li class="compare_text"> 
									<a rel="nofollow" href="<?php echo $_compareUrl ?>" class="link-compare">
										<?php echo $this->__('Add to Compare') ?>	</a>	
									</li>							
									<?php endif; ?>
									
								<?php endif; ?>
							<?php endif; ?>
							
						</ul>
					<?php endif; ?>
                </div>
			</div>
			
			<div class="products_list_right">
				  <?php echo $this->getPriceHtml($_product, true) ?>
				  <?php if($_product->isSaleable()): ?>
                        <p>
						<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span class="availability"><span class="value-title" title="In Stock"><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
			</div>
			
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>

        <?php if ($i++%$_columnCount==0): ?>
		<ul class="products-grid category-products-grid itemgrid-3cols">
        <?php endif ?>
		
    <?php $i=0; foreach ($_productCollection as $_product):  $i++;?>

            <li class="hproduct grid-item item">
			<div class="product-block">
				<div class="product-block-inner">
				
				
							<h2 class="fn product-name" >
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName())?></a></h2>
                
				
				<div class="product_back">
				<div  class="product_iner">
				
				<!-- =============  Start New / Sale Label ===== -->
					<?php if($this->helper('framework')->isSpecialProduct($_product)):?>
						<div class="sale-label"><?php echo $this->__('Sale Label') ?></div>
					<?php endif; ?>	
				<!-- =============  End New / Sale Label ===== -->
                 
				<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image url">
				<?php if($this->helper('framework')->getAspectRatio()):?>				
					<img class="photo fn" src="<?php echo $this->helper('adaptiveResize/image')->init($_product, 'small_image')->setCropPosition('top')->adaptiveResize(200,240); ?>" width="200" height="240" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
				<?php else:	?>	
					<img class="photo fn" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(220,290); ?>" width="220" height="290" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />				
				<?php endif; ?>	
				
				</a>
				</div>
				</div>
                
	
				<?php if($_product->getRatingSummary()): ?>
                <div class="description grid_rating">
					<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
				</div>
                <?php endif; ?>
                
				<?php echo $this->getPriceHtml($_product, true) ?>
				
				 
                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                   
				   
				   <?php if($this->helper('framework')->getAddtoLinksGridIcon()):?>
				 	 <div class="actions_image">
				 <?php else: ?>
				 	 <div class="actions">
				 <?php endif; ?>
				   
				  <?php if($this->helper('framework')->getAddtoLinksGrid()):?>
				   
                    <ul class="add-to-links">
						<?php if(!$this->helper('framework')->isActiveWishlist()):?>
							<?php if ($this->helper('wishlist')->isAllow()) : ?>
							
								<?php if($this->helper('framework')->getAddtoLinksGridIcon()):?>
										<li class="wishlist_image">
											<a rel="nofollow" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>">
											<img src="<?php echo $this->getSkinUrl('images/link_wishlist_icon.png')?>" alt="" />
											</a>
										</li>
									<?php else: ?>
										<li class="wishlist_text">
										<a rel="nofollow" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist">
											<?php echo $this->__('Add to Wishlist') ?></a>
										</li>
									<?php endif; ?>
									
							<?php endif; ?>
						<?php endif; ?>
						
						<?php if(!$this->helper('framework')->isActiveCompare()):?>
							<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
								
								<?php if($this->helper('framework')->getAddtoLinksGridIcon()):?>
									<li class="compare_image">
										<a rel="nofollow" href="<?php echo $_compareUrl ?>" class="link-compare">
											<img src="<?php echo $this->getSkinUrl('images/link_compare_icon.png')?>" alt="" />
										</a>
									</li>	
									<?php else: ?>
										<li class="compare_text">
										<a rel="nofollow" href="<?php echo $_compareUrl ?>" class="link-compare">
											<?php echo $this->__('Add to Compare') ?></a>
										</li>	
									<?php endif; ?>
									</a>
								
							<?php endif; ?>
						<?php endif; ?>							
						
                    </ul>
				 
					<?php endif; ?>
				   
				   
                 
				
				</div>
				</div>
				</div>
            </li>

        <?php endforeach ?>
		
		
        
        </ul>
        
		
        
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</article>

<?php endif; ?>

<?php 
$fixCol = 3;
$column = $this->helper('framework')->getProductPerRow(); 
$html = '';
if($fixCol > $column ){		
	$nCol = $fixCol - $column; 	
	$html.='-'.$nCol;
}	
else if($fixCol < $column ){
	$nCol = $column - $fixCol;
	$html.='+'.$nCol;	
}
?>

<script type="text/javascript">
	 function smartRowsColumns($) { 
		$("ul.products-grid").css({ 'width' : "100%"});
		var colWrap = $("ul.products-grid").width(); 
		var curMargin = parseInt($("ul.products-grid li.item .product-block").css("margin-left"));
		var curWidth = 226;  // 256 is default width minus Margins
		var colNum = Math.floor(colWrap / curWidth)<?php echo $html;?>; 
		var colFixed = Math.floor(colWrap / colNum); 
		$("ul.products-grid").css({ 'width' : colWrap});
		$("ul.products-grid li.item").css({ 'width' : colFixed}); 
		
		if ($(window).width() >= 480)
		{
			var colMaxHeight = 0;
			$('.products-grid .item').each(function() {
				//$(this).css("height", "auto");
				colMaxHeight = Math.max(colMaxHeight, $(this).height());
			});
			$('.products-grid .item').css("height", colMaxHeight + "px");
			$('.products-grid .item .product-block').css("height", colMaxHeight + "px");
			
		}
		else
		{
			$('.products-grid .item').css("height", "auto");
			$('.products-grid .item .product-block').css("height", "auto");
		}
		
	 }
	jQuery(function($) {
		$(window).resize(function() {
			smartRowsColumns($);
			
		});
	}); 
	jQuery(window).load(function(){
		smartRowsColumns(jQuery);
	}); 
</script>