<?php if($this->enablespecialslider()): ?>
<!-- ================================== Slider Content ========================= -->
<?php if (($_products = $this->getSpecialProductCollection()) && $_products->getSize()): ?>
<div class="block block-related" id="left_specialproduct">
    <div class="block-title">
        <strong><span><?php echo $this->getSidebarHeading(); ?></span></strong>
    </div>
    <div class="block-content">      
        <ul class="mini-products-list mycarousel" id="block-specialproducts">
        <?php foreach ($_products as $_item): ?>
            <li class="item">                
                <div class="product" style="margin-left: 0px;">
                    <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(50) ?>" width="50" height="50" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" /></a>
					
                    <div class="product-details">
                    <p class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></p>
					
					<?php if($this->getPriceDisplay()): ?>
						<div class="price-box"><span class="price"><?php echo Mage::helper('core')->currency($_item->price, true, false); ?></span></div>
					<?php endif; ?>
					
					<?php if($this->getAddtocart()): ?>
						<?php if($_item->isSaleable()): ?>
						<a href="<?php echo Mage::getUrl('checkout/cart/add', array('product'=>$_item->getEntityId(),'qty'=>1)) ?>" title="<?php echo $this->__('Add to Cart') ?>"  rel="nofollow" class="addto-cart"><?php echo $this->__('Add to Cart') ?></a></p>
						<?php endif; ?>
					<?php endif; ?>	
                    </div>
					
                </div>
            </li>
        <?php endforeach ?>
        </ul>
        <script type="text/javascript">decorateList('block-specialproducts', 'none-recursive')</script>
    </div>    
</div>
<?php endif ?>


<?php else: ?>
<?php if (($_products = $this->getSpecialProductCollection()) && $_products->getSize()): ?>
<div class="block block-related">
    <div class="block-title">
        <strong><span><?php echo $this->getSidebarHeading(); ?></span></strong>
    </div>
    <div class="block-content">      
        <ol class="mini-products-list" id="block-specialproducts">
        <?php foreach ($_products as $_item): ?>
            <li class="item">                
                <div class="product" style="margin-left: 0px;">
                    <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(50) ?>" width="50" height="50" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" /></a>
					
                    <div class="product-details">
                    <p class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></p>
					
					<?php if($this->getPriceDisplay()): ?>
						<div class="price-box"><span class="price"><?php echo Mage::helper('core')->currency($_item->price, true, false); ?></span></div>
					<?php endif; ?>
					
					<?php if($this->getAddtocart()): ?>
						<?php if($_item->isSaleable()): ?>
						<p><a href="<?php echo Mage::getUrl('checkout/cart/add', array('product'=>$_item->getEntityId(),'qty'=>1)) ?>" title="<?php echo $this->__('Add to Cart') ?>"  rel="nofollow" class="addto-cart"><?php echo $this->__('Add to Cart') ?></a></p>
						<?php endif; ?>
					<?php endif; ?>	
                    </div>
					
                </div>
            </li>
        <?php endforeach ?>
        </ol>
        <script type="text/javascript">decorateList('block-specialproducts', 'none-recursive')</script>
    </div>    
</div>
<?php endif ?>

<?php endif ?>
