<?php
/**
 * TemplateMela
 * @copyright  Copyright (c) 2010 TemplateMela. (http://www.templatemela.com)
 * @license    http://www.templatemela.com/license/
 */
 
?>
<?php 
$_helper = $this->helper('catalog/output');
$attrCode = Mage::getStoreConfig('template_settings/products_info_page/custom_tab_code');
if($attrCode){
	$product = $this->getProduct();
	$attribute = $product->getResource()->getAttribute($attrCode);
	if ($attribute) {
		$content = $attribute->getFrontend()->getValue($product);
		if(!empty($content)){
			echo '<div class="product-specs">'
				. $_helper->productAttribute($this->getProduct(), $content, $attrCode)
				. '</div>';
		}
	}
}
?>