<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<!-- ======================== CMS TOP BLOCK ============================= -->

<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<article class="category-products">
<div class="spinner"></div>
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
	<ol class="products-list" id="products-list">    
    <?php foreach ($_productCollection as $_product): ?>
        <li class="hproduct item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
			
			
            <div class="products_list_left">
			<?php if($this->helper('framework')->isNewProduct($_product)):?>
					<div class="new-label"><?php echo $this->__('New Label') ?></div>
			<?php endif; ?>
				
			<?php if($this->helper('framework')->isSpecialProduct($_product)):?>
					<div class="sale-label"><?php echo $this->__('Sale Label') ?></div>
			<?php endif; ?>	
			<?php // Product Image ?>
			
				<div class="product_back">
				<div class="product_iner">
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image url">
							
				<?php if($this->helper('framework')->getAspectRatio()):?>				
					<img class="photo fn" src="<?php echo $this->helper('adaptiveResize/image')->init($_product, 'small_image')->setCropPosition('top')->adaptiveResize(180,200); ?>" width="180" height="200" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
				<?php else:	?>	
					<img class="photo fn" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(180,180); ?>" width="180" height="180" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />			
				<?php endif; ?>	 
				</a>
				</div>
				</div>
				
			</div>	
            <?php // Product description ?>
           <div class="products_list_center">
                <div class="f-fix">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="item fn product-name" ><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                    <?php if($_product->getRatingSummary()): ?>
                    <div class="description"><?php echo $this->getReviewsSummaryHtml($_product) ?></div>
                    <?php endif; ?>
					
					<?php echo $this->helper('framework')->getProductAttribute($_product, $_product->_data['short_description']);?>
					
                    <div class="desc std">
					  <?php 
							$str = strlen($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'));
							if($str <= 300 )
							{
								echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description')  ?>						
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn">
									<?php echo $this->__('Learn More') ?>
								</a>
							<?php }
							else
							{
								echo substr($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'),0,300);  ?>							
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn">
								 <?php echo $this->__('Learn More') ?>
							   </a>
						<?php } ?>
                    </div>
					
					<?php if($this->helper('framework')->getAddtoLinksList()):?>
						<ul class="add-to-links">
							<?php if(!$this->helper('framework')->isActiveWishlist()):?>						
								<?php if ($this->helper('wishlist')->isAllow()) : ?>
									
									<?php if($this->helper('framework')->getAddtoLinksListIcon()):?>
										<li class="wishlist_image">
											<a rel="nofollow"  href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>">
											<img src="<?php echo $this->getSkinUrl('images/link_wishlist_icon.png')?>" alt="" /></a>
										</li>	
									<?php else: ?>
										<li class="wishlist_text">
										<a rel="nofollow"  href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist">
										<?php echo $this->__('Add to Wishlist') ?></li></a>
									<?php endif; ?>
										
								<?php endif; ?>
							<?php endif; ?>	
							
							<?php if(!$this->helper('framework')->isActiveCompare()):?>
								<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
								
								<?php if($this->helper('framework')->getAddtoLinksListIcon()):?>
									<li class="compare_image">
										<a rel="nofollow" href="<?php echo $_compareUrl ?>">
											<img src="<?php echo $this->getSkinUrl('images/link_compare_icon.png')?>" alt="" />										
										</a>
									</li>	
									<?php else: ?>
									<li class="compare_text"> 
									<a rel="nofollow" href="<?php echo $_compareUrl ?>" class="link-compare">
										<?php echo $this->__('Add to Compare') ?>	</a>	
									</li>							
									<?php endif; ?>
									
								<?php endif; ?>
							<?php endif; ?>
							
						</ul>
					<?php endif; ?>
					
                </div>
            </div>
			
			<div class="products_list_right">

			  	<?php echo $this->getPriceHtml($_product, true) ?>
				
				<?php if($_product->isSaleable()): ?>
					<p class="addlink">
					<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span class="availability"><span class="value-title" title="In Stock"><?php echo $this->__('Add to Cart') ?></span></span></button></p>
				<?php else: ?>
					<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
				<?php endif; ?>
				
			</div>
			
			
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>
<?php
	$grid_imagewidth = $this->helper('framework')->getProductgridimagewidth(); 
	$grid_imageheight = $this->helper('framework')->getProductgridimageheight(); 
?>
    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>

        <?php if ($i++%$_columnCount==0): ?>
		<ul class="products-grid">
        <?php endif ?>
		
    <?php $i=0; foreach ($_productCollection as $_product):  $i++;?>
			<?php $number_columns = $this->helper('framework')->getProductPerRow(); ?>
            <li class="hproduct grid-item item item_<?php echo $number_columns;?>columns">
			
			<div class="product-block">
			
				<div class="product-block-inner">	
				
				  
				
				<div class="product_back">
				<div  class="product_iner">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" class="product-image url"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(220,220); ?>" width="200" height="200" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" /></a>
                </div>
				<!-- Titlu -->
				<h2 class="fn product-name" ><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
				
				<?php if($this->helper('framework')->isNewProduct($_product)):?>
					<div class="new-label"><?php echo $this->__('New Label') ?></div>
				<?php endif; ?>
				
				<?php if($this->helper('framework')->isSpecialProduct($_product)):?>
					<div class="sale-label"><?php echo $this->__('Sale Label') ?></div>
				<?php endif; ?>	
				<!-- Sfarsit titlu -->
				</div>	<!-- Descriere produs -->
				<div class="shortDescription">
	                <?php echo nl2br($_product->getShortDescription()); ?>
                </div>
			<!-- Sfarsit descriere produs -->
				  
				 <?php echo $this->getPriceHtml($_product, true) ?>
				  
				<?php if($_product->getRatingSummary()): ?>
					<div class="description grid_rating">
						<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
					</div>
                <?php endif; ?>
                
				<?php echo $this->helper('framework')->getProductAttribute($_product, $_product->_data['short_description']);?>
				
				 
				<div class="actions">
                    <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
					</div>
				
				<br \>
		            <span class="disponibilitatefloat2">Disponibilitate:</span>
        		    <span class="spandisponibilitate"><strong><?php echo $_product->getAttributeText('stoc_cluj') ?></strong></span>
            		<br \>
                
				 <?php if($this->helper('framework')->getAddtoLinksGridIcon()):?>
				 	 <div class="actions_image">
				 <?php else: ?>
				 	 <div class="actions">
				 <?php endif; ?>
				
					
				
					<div class="actions">
                    <?php if ($this->helper('wishlist')->isAllow() && $this->getAddToCompareUrl($_product)) : ?>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>
                    <?php endif; ?>
                </div>			
					 
				
				
				</div>
				
				</div>
				</div>
            </li>

        <?php endforeach ?>
		
		
        
        </ul>
        
		
        
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</article>
<?php endif; ?>

<!-- ============= BOTTOM CMS BLOCK ================== -->
<!--<div class="bottom_static_block">
	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('tm_productlist_bottomblock')->toHtml() ?> 

</div>-->


<?php 
$fixCol = 3;
$column = $this->helper('framework')->getProductPerRow(); 
$html = '';
if($fixCol > $column ){		
	$nCol = $fixCol - $column; 	
	$html.='-'.$nCol;
}	
else if($fixCol < $column ){
	$nCol = $column - $fixCol;
	$html.='+'.$nCol;	
}

?>


<script type="text/javascript">
	 function smartRowsColumns($) { 
		$("ul.products-grid").css({ 'width' : "100%"});
		var colWrap = $("ul.products-grid").width(); 
		var curMargin = parseInt($("ul.products-grid li.item .product-block").css("margin-left"));
		var curWidth = 226;  // 256 is default width minus Margins
		var colNum = Math.floor(colWrap / curWidth)<?php echo $html;?>; 
		var colFixed = Math.floor(colWrap / colNum); 
		$("ul.products-grid").css({ 'width' : colWrap});
		$("ul.products-grid li.item").css({ 'width' : colFixed}); 
		
		if ($(window).width() >= 480)
		{
			var colMaxHeight = 0;
			$('.products-grid .item').each(function() {
				//$(this).css("height", "auto");
				colMaxHeight = Math.max(colMaxHeight, $(this).height());
			});
			$('.products-grid .item').css("height", colMaxHeight + "px");
			$('.products-grid .item .product-block').css("height", colMaxHeight + "px");
			
		}
		else
		{
			$('.products-grid .item').css("height", "auto");
			$('.products-grid .item .product-block').css("height", "auto");
			//$('.products-grid .item').css("height", colFixed + "px");
			//$('.products-grid .item .product-block').css("height", colFixed + "px");
		}
		
	 }
	jQuery(function($) {
		$(window).resize(function() {
			smartRowsColumns($);
			
		});
	}); 
	jQuery(window).load(function(){
		smartRowsColumns(jQuery);
	}); 
	
	
 
</script>